name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - name: Setup Flutter
        run: |
          cd giant_arrow
          flutter pub get
          flutter doctor
          flutter clean
          flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: giant_arrow/ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign
        working-directory: giant_arrow

      - name: Create Payload Directory
        run: mkdir -p Payload
        working-directory: giant_arrow/build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app/ Payload
        working-directory: giant_arrow/build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: giant_arrow/build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: giant_arrow/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS build release"
